apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - uses: cloudbees-io/checkout@v1 
      - name: build
        uses: docker://maven:3.9.4-eclipse-temurin-17-alpine
        run: |
          mvn clean install